### PR TITLE
Scala and sbt upgrades

### PR DESCRIPTION
**Pull request by tgalery**
Connects to https://github.com/idio/idio/issues/915 but it seems we need to upgrade our scala version across the board.

### CODE REVIEW

**Comment by tgalery** [comment]
See https://github.com/idio/idio/issues/915#issuecomment-369623491

**Comment by rooagarw** [comment]
please merge this

**Comment by rooagarw** [comment]
need upgraded versions for this library

**Comment by bpholt** [comment]
FYI, #10 supersedes this pull request, since it cross-publishes for both sbt 1.x and 0.13, while this one ends support for 0.13.

**Pull request closed without merging**
